/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AuthStudentsIndexRouteImport } from './routes/_auth/students/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthStudentsMyCoursesRouteImport } from './routes/_auth/students/my-courses'
import { Route as AuthStudentsAllCoursesRouteImport } from './routes/_auth/students/all-courses'
import { Route as AuthAdminStudentsRouteImport } from './routes/_auth/admin/students'
import { Route as AuthAdminAllCoursesRouteImport } from './routes/_auth/admin/all-courses'
import { Route as AuthAdminCoursesIndexRouteImport } from './routes/_auth/admin/courses/index'
import { Route as AuthStudentsCourseCourseIdRouteImport } from './routes/_auth/students/course/$courseId'
import { Route as AuthStudentsCourseLessonLessonIdRouteImport } from './routes/_auth/students/course/lesson/$lessonId'
import { Route as AuthAdminCoursesManageCourseIdRouteImport } from './routes/_auth/admin/courses/manage/$courseId'
import { Route as AuthAdminCoursesManageCourseIdLessonsLessonIdRouteImport } from './routes/_auth/admin/courses/manage/$courseId/lessons/$lessonId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthStudentsIndexRoute = AuthStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsMyCoursesRoute = AuthStudentsMyCoursesRouteImport.update({
  id: '/students/my-courses',
  path: '/students/my-courses',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsAllCoursesRoute = AuthStudentsAllCoursesRouteImport.update({
  id: '/students/all-courses',
  path: '/students/all-courses',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminStudentsRoute = AuthAdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminAllCoursesRoute = AuthAdminAllCoursesRouteImport.update({
  id: '/admin/all-courses',
  path: '/admin/all-courses',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminCoursesIndexRoute = AuthAdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsCourseCourseIdRoute =
  AuthStudentsCourseCourseIdRouteImport.update({
    id: '/students/course/$courseId',
    path: '/students/course/$courseId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthStudentsCourseLessonLessonIdRoute =
  AuthStudentsCourseLessonLessonIdRouteImport.update({
    id: '/students/course/lesson/$lessonId',
    path: '/students/course/lesson/$lessonId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminCoursesManageCourseIdRoute =
  AuthAdminCoursesManageCourseIdRouteImport.update({
    id: '/admin/courses/manage/$courseId',
    path: '/admin/courses/manage/$courseId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminCoursesManageCourseIdLessonsLessonIdRoute =
  AuthAdminCoursesManageCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthAdminCoursesManageCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/all-courses': typeof AuthAdminAllCoursesRoute
  '/admin/students': typeof AuthAdminStudentsRoute
  '/students/all-courses': typeof AuthStudentsAllCoursesRoute
  '/students/my-courses': typeof AuthStudentsMyCoursesRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/students/': typeof AuthStudentsIndexRoute
  '/students/course/$courseId': typeof AuthStudentsCourseCourseIdRoute
  '/admin/courses/': typeof AuthAdminCoursesIndexRoute
  '/admin/courses/manage/$courseId': typeof AuthAdminCoursesManageCourseIdRouteWithChildren
  '/students/course/lesson/$lessonId': typeof AuthStudentsCourseLessonLessonIdRoute
  '/admin/courses/manage/$courseId/lessons/$lessonId': typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/all-courses': typeof AuthAdminAllCoursesRoute
  '/admin/students': typeof AuthAdminStudentsRoute
  '/students/all-courses': typeof AuthStudentsAllCoursesRoute
  '/students/my-courses': typeof AuthStudentsMyCoursesRoute
  '/admin': typeof AuthAdminIndexRoute
  '/students': typeof AuthStudentsIndexRoute
  '/students/course/$courseId': typeof AuthStudentsCourseCourseIdRoute
  '/admin/courses': typeof AuthAdminCoursesIndexRoute
  '/admin/courses/manage/$courseId': typeof AuthAdminCoursesManageCourseIdRouteWithChildren
  '/students/course/lesson/$lessonId': typeof AuthStudentsCourseLessonLessonIdRoute
  '/admin/courses/manage/$courseId/lessons/$lessonId': typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/admin/all-courses': typeof AuthAdminAllCoursesRoute
  '/_auth/admin/students': typeof AuthAdminStudentsRoute
  '/_auth/students/all-courses': typeof AuthStudentsAllCoursesRoute
  '/_auth/students/my-courses': typeof AuthStudentsMyCoursesRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/students/': typeof AuthStudentsIndexRoute
  '/_auth/students/course/$courseId': typeof AuthStudentsCourseCourseIdRoute
  '/_auth/admin/courses/': typeof AuthAdminCoursesIndexRoute
  '/_auth/admin/courses/manage/$courseId': typeof AuthAdminCoursesManageCourseIdRouteWithChildren
  '/_auth/students/course/lesson/$lessonId': typeof AuthStudentsCourseLessonLessonIdRoute
  '/_auth/admin/courses/manage/$courseId/lessons/$lessonId': typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/all-courses'
    | '/admin/students'
    | '/students/all-courses'
    | '/students/my-courses'
    | '/admin/'
    | '/students/'
    | '/students/course/$courseId'
    | '/admin/courses/'
    | '/admin/courses/manage/$courseId'
    | '/students/course/lesson/$lessonId'
    | '/admin/courses/manage/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/all-courses'
    | '/admin/students'
    | '/students/all-courses'
    | '/students/my-courses'
    | '/admin'
    | '/students'
    | '/students/course/$courseId'
    | '/admin/courses'
    | '/admin/courses/manage/$courseId'
    | '/students/course/lesson/$lessonId'
    | '/admin/courses/manage/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/login'
    | '/register'
    | '/_public/'
    | '/_auth/admin/all-courses'
    | '/_auth/admin/students'
    | '/_auth/students/all-courses'
    | '/_auth/students/my-courses'
    | '/_auth/admin/'
    | '/_auth/students/'
    | '/_auth/students/course/$courseId'
    | '/_auth/admin/courses/'
    | '/_auth/admin/courses/manage/$courseId'
    | '/_auth/students/course/lesson/$lessonId'
    | '/_auth/admin/courses/manage/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/students/': {
      id: '/_auth/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthStudentsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/my-courses': {
      id: '/_auth/students/my-courses'
      path: '/students/my-courses'
      fullPath: '/students/my-courses'
      preLoaderRoute: typeof AuthStudentsMyCoursesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/all-courses': {
      id: '/_auth/students/all-courses'
      path: '/students/all-courses'
      fullPath: '/students/all-courses'
      preLoaderRoute: typeof AuthStudentsAllCoursesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/students': {
      id: '/_auth/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthAdminStudentsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/all-courses': {
      id: '/_auth/admin/all-courses'
      path: '/admin/all-courses'
      fullPath: '/admin/all-courses'
      preLoaderRoute: typeof AuthAdminAllCoursesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/courses/': {
      id: '/_auth/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthAdminCoursesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/course/$courseId': {
      id: '/_auth/students/course/$courseId'
      path: '/students/course/$courseId'
      fullPath: '/students/course/$courseId'
      preLoaderRoute: typeof AuthStudentsCourseCourseIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/course/lesson/$lessonId': {
      id: '/_auth/students/course/lesson/$lessonId'
      path: '/students/course/lesson/$lessonId'
      fullPath: '/students/course/lesson/$lessonId'
      preLoaderRoute: typeof AuthStudentsCourseLessonLessonIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/courses/manage/$courseId': {
      id: '/_auth/admin/courses/manage/$courseId'
      path: '/admin/courses/manage/$courseId'
      fullPath: '/admin/courses/manage/$courseId'
      preLoaderRoute: typeof AuthAdminCoursesManageCourseIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/courses/manage/$courseId/lessons/$lessonId': {
      id: '/_auth/admin/courses/manage/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/courses/manage/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AuthAdminCoursesManageCourseIdRoute
    }
  }
}

interface AuthAdminCoursesManageCourseIdRouteChildren {
  AuthAdminCoursesManageCourseIdLessonsLessonIdRoute: typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRoute
}

const AuthAdminCoursesManageCourseIdRouteChildren: AuthAdminCoursesManageCourseIdRouteChildren =
  {
    AuthAdminCoursesManageCourseIdLessonsLessonIdRoute:
      AuthAdminCoursesManageCourseIdLessonsLessonIdRoute,
  }

const AuthAdminCoursesManageCourseIdRouteWithChildren =
  AuthAdminCoursesManageCourseIdRoute._addFileChildren(
    AuthAdminCoursesManageCourseIdRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAdminAllCoursesRoute: typeof AuthAdminAllCoursesRoute
  AuthAdminStudentsRoute: typeof AuthAdminStudentsRoute
  AuthStudentsAllCoursesRoute: typeof AuthStudentsAllCoursesRoute
  AuthStudentsMyCoursesRoute: typeof AuthStudentsMyCoursesRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthStudentsIndexRoute: typeof AuthStudentsIndexRoute
  AuthStudentsCourseCourseIdRoute: typeof AuthStudentsCourseCourseIdRoute
  AuthAdminCoursesIndexRoute: typeof AuthAdminCoursesIndexRoute
  AuthAdminCoursesManageCourseIdRoute: typeof AuthAdminCoursesManageCourseIdRouteWithChildren
  AuthStudentsCourseLessonLessonIdRoute: typeof AuthStudentsCourseLessonLessonIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminAllCoursesRoute: AuthAdminAllCoursesRoute,
  AuthAdminStudentsRoute: AuthAdminStudentsRoute,
  AuthStudentsAllCoursesRoute: AuthStudentsAllCoursesRoute,
  AuthStudentsMyCoursesRoute: AuthStudentsMyCoursesRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthStudentsIndexRoute: AuthStudentsIndexRoute,
  AuthStudentsCourseCourseIdRoute: AuthStudentsCourseCourseIdRoute,
  AuthAdminCoursesIndexRoute: AuthAdminCoursesIndexRoute,
  AuthAdminCoursesManageCourseIdRoute:
    AuthAdminCoursesManageCourseIdRouteWithChildren,
  AuthStudentsCourseLessonLessonIdRoute: AuthStudentsCourseLessonLessonIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
