/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as AuthStudentsIndexRouteImport } from './routes/_auth/students/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthStudentsMyCoursesRouteImport } from './routes/_auth/students/my-courses'
import { Route as AuthStudentsAllCoursesRouteImport } from './routes/_auth/students/all-courses'
import { Route as AuthAdminStudentsRouteImport } from './routes/_auth/admin/students'
import { Route as AuthAdminAllCoursesRouteImport } from './routes/_auth/admin/all-courses'
import { Route as AuthAdminServicesIndexRouteImport } from './routes/_auth/admin/services/index'
import { Route as AuthAdminCoursesIndexRouteImport } from './routes/_auth/admin/courses/index'
import { Route as AuthStudentsCourseCourseIdRouteImport } from './routes/_auth/students/course/$courseId'
import { Route as AuthAdminServicesServiceIdRouteImport } from './routes/_auth/admin/services/$serviceId'
import { Route as AuthStudentsCourseLessonLessonIdRouteImport } from './routes/_auth/students/course/lesson/$lessonId'
import { Route as AuthAdminCoursesManageCourseIdRouteImport } from './routes/_auth/admin/courses/manage/$courseId'
import { Route as AuthAdminCoursesManageCourseIdLessonsLessonIdRouteImport } from './routes/_auth/admin/courses/manage/$courseId/lessons/$lessonId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthStudentsIndexRoute = AuthStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsMyCoursesRoute = AuthStudentsMyCoursesRouteImport.update({
  id: '/students/my-courses',
  path: '/students/my-courses',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsAllCoursesRoute = AuthStudentsAllCoursesRouteImport.update({
  id: '/students/all-courses',
  path: '/students/all-courses',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminStudentsRoute = AuthAdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminAllCoursesRoute = AuthAdminAllCoursesRouteImport.update({
  id: '/admin/all-courses',
  path: '/admin/all-courses',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminServicesIndexRoute = AuthAdminServicesIndexRouteImport.update({
  id: '/admin/services/',
  path: '/admin/services/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminCoursesIndexRoute = AuthAdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsCourseCourseIdRoute =
  AuthStudentsCourseCourseIdRouteImport.update({
    id: '/students/course/$courseId',
    path: '/students/course/$courseId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminServicesServiceIdRoute =
  AuthAdminServicesServiceIdRouteImport.update({
    id: '/admin/services/$serviceId',
    path: '/admin/services/$serviceId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthStudentsCourseLessonLessonIdRoute =
  AuthStudentsCourseLessonLessonIdRouteImport.update({
    id: '/students/course/lesson/$lessonId',
    path: '/students/course/lesson/$lessonId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminCoursesManageCourseIdRoute =
  AuthAdminCoursesManageCourseIdRouteImport.update({
    id: '/admin/courses/manage/$courseId',
    path: '/admin/courses/manage/$courseId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminCoursesManageCourseIdLessonsLessonIdRoute =
  AuthAdminCoursesManageCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthAdminCoursesManageCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/all-courses': typeof AuthAdminAllCoursesRoute
  '/admin/students': typeof AuthAdminStudentsRoute
  '/students/all-courses': typeof AuthStudentsAllCoursesRoute
  '/students/my-courses': typeof AuthStudentsMyCoursesRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/students/': typeof AuthStudentsIndexRoute
  '/admin/services/$serviceId': typeof AuthAdminServicesServiceIdRoute
  '/students/course/$courseId': typeof AuthStudentsCourseCourseIdRoute
  '/admin/courses/': typeof AuthAdminCoursesIndexRoute
  '/admin/services/': typeof AuthAdminServicesIndexRoute
  '/admin/courses/manage/$courseId': typeof AuthAdminCoursesManageCourseIdRouteWithChildren
  '/students/course/lesson/$lessonId': typeof AuthStudentsCourseLessonLessonIdRoute
  '/admin/courses/manage/$courseId/lessons/$lessonId': typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/courses': typeof CoursesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/all-courses': typeof AuthAdminAllCoursesRoute
  '/admin/students': typeof AuthAdminStudentsRoute
  '/students/all-courses': typeof AuthStudentsAllCoursesRoute
  '/students/my-courses': typeof AuthStudentsMyCoursesRoute
  '/admin': typeof AuthAdminIndexRoute
  '/students': typeof AuthStudentsIndexRoute
  '/admin/services/$serviceId': typeof AuthAdminServicesServiceIdRoute
  '/students/course/$courseId': typeof AuthStudentsCourseCourseIdRoute
  '/admin/courses': typeof AuthAdminCoursesIndexRoute
  '/admin/services': typeof AuthAdminServicesIndexRoute
  '/admin/courses/manage/$courseId': typeof AuthAdminCoursesManageCourseIdRouteWithChildren
  '/students/course/lesson/$lessonId': typeof AuthStudentsCourseLessonLessonIdRoute
  '/admin/courses/manage/$courseId/lessons/$lessonId': typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/_public/': typeof PublicIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_auth/admin/all-courses': typeof AuthAdminAllCoursesRoute
  '/_auth/admin/students': typeof AuthAdminStudentsRoute
  '/_auth/students/all-courses': typeof AuthStudentsAllCoursesRoute
  '/_auth/students/my-courses': typeof AuthStudentsMyCoursesRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/students/': typeof AuthStudentsIndexRoute
  '/_auth/admin/services/$serviceId': typeof AuthAdminServicesServiceIdRoute
  '/_auth/students/course/$courseId': typeof AuthStudentsCourseCourseIdRoute
  '/_auth/admin/courses/': typeof AuthAdminCoursesIndexRoute
  '/_auth/admin/services/': typeof AuthAdminServicesIndexRoute
  '/_auth/admin/courses/manage/$courseId': typeof AuthAdminCoursesManageCourseIdRouteWithChildren
  '/_auth/students/course/lesson/$lessonId': typeof AuthStudentsCourseLessonLessonIdRoute
  '/_auth/admin/courses/manage/$courseId/lessons/$lessonId': typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/contact'
    | '/courses/$courseId'
    | '/services/$serviceId'
    | '/courses/'
    | '/services/'
    | '/admin/all-courses'
    | '/admin/students'
    | '/students/all-courses'
    | '/students/my-courses'
    | '/admin/'
    | '/students/'
    | '/admin/services/$serviceId'
    | '/students/course/$courseId'
    | '/admin/courses/'
    | '/admin/services/'
    | '/admin/courses/manage/$courseId'
    | '/students/course/lesson/$lessonId'
    | '/admin/courses/manage/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/contact'
    | '/courses/$courseId'
    | '/services/$serviceId'
    | '/courses'
    | '/services'
    | '/admin/all-courses'
    | '/admin/students'
    | '/students/all-courses'
    | '/students/my-courses'
    | '/admin'
    | '/students'
    | '/admin/services/$serviceId'
    | '/students/course/$courseId'
    | '/admin/courses'
    | '/admin/services'
    | '/admin/courses/manage/$courseId'
    | '/students/course/lesson/$lessonId'
    | '/admin/courses/manage/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/login'
    | '/register'
    | '/_public/about'
    | '/_public/contact'
    | '/courses/$courseId'
    | '/services/$serviceId'
    | '/_public/'
    | '/courses/'
    | '/services/'
    | '/_auth/admin/all-courses'
    | '/_auth/admin/students'
    | '/_auth/students/all-courses'
    | '/_auth/students/my-courses'
    | '/_auth/admin/'
    | '/_auth/students/'
    | '/_auth/admin/services/$serviceId'
    | '/_auth/students/course/$courseId'
    | '/_auth/admin/courses/'
    | '/_auth/admin/services/'
    | '/_auth/admin/courses/manage/$courseId'
    | '/_auth/students/course/lesson/$lessonId'
    | '/_auth/admin/courses/manage/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/students/': {
      id: '/_auth/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthStudentsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/my-courses': {
      id: '/_auth/students/my-courses'
      path: '/students/my-courses'
      fullPath: '/students/my-courses'
      preLoaderRoute: typeof AuthStudentsMyCoursesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/all-courses': {
      id: '/_auth/students/all-courses'
      path: '/students/all-courses'
      fullPath: '/students/all-courses'
      preLoaderRoute: typeof AuthStudentsAllCoursesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/students': {
      id: '/_auth/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthAdminStudentsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/all-courses': {
      id: '/_auth/admin/all-courses'
      path: '/admin/all-courses'
      fullPath: '/admin/all-courses'
      preLoaderRoute: typeof AuthAdminAllCoursesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/services/': {
      id: '/_auth/admin/services/'
      path: '/admin/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AuthAdminServicesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/courses/': {
      id: '/_auth/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthAdminCoursesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/course/$courseId': {
      id: '/_auth/students/course/$courseId'
      path: '/students/course/$courseId'
      fullPath: '/students/course/$courseId'
      preLoaderRoute: typeof AuthStudentsCourseCourseIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/services/$serviceId': {
      id: '/_auth/admin/services/$serviceId'
      path: '/admin/services/$serviceId'
      fullPath: '/admin/services/$serviceId'
      preLoaderRoute: typeof AuthAdminServicesServiceIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/course/lesson/$lessonId': {
      id: '/_auth/students/course/lesson/$lessonId'
      path: '/students/course/lesson/$lessonId'
      fullPath: '/students/course/lesson/$lessonId'
      preLoaderRoute: typeof AuthStudentsCourseLessonLessonIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/courses/manage/$courseId': {
      id: '/_auth/admin/courses/manage/$courseId'
      path: '/admin/courses/manage/$courseId'
      fullPath: '/admin/courses/manage/$courseId'
      preLoaderRoute: typeof AuthAdminCoursesManageCourseIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/courses/manage/$courseId/lessons/$lessonId': {
      id: '/_auth/admin/courses/manage/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/courses/manage/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AuthAdminCoursesManageCourseIdRoute
    }
  }
}

interface AuthAdminCoursesManageCourseIdRouteChildren {
  AuthAdminCoursesManageCourseIdLessonsLessonIdRoute: typeof AuthAdminCoursesManageCourseIdLessonsLessonIdRoute
}

const AuthAdminCoursesManageCourseIdRouteChildren: AuthAdminCoursesManageCourseIdRouteChildren =
  {
    AuthAdminCoursesManageCourseIdLessonsLessonIdRoute:
      AuthAdminCoursesManageCourseIdLessonsLessonIdRoute,
  }

const AuthAdminCoursesManageCourseIdRouteWithChildren =
  AuthAdminCoursesManageCourseIdRoute._addFileChildren(
    AuthAdminCoursesManageCourseIdRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAdminAllCoursesRoute: typeof AuthAdminAllCoursesRoute
  AuthAdminStudentsRoute: typeof AuthAdminStudentsRoute
  AuthStudentsAllCoursesRoute: typeof AuthStudentsAllCoursesRoute
  AuthStudentsMyCoursesRoute: typeof AuthStudentsMyCoursesRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthStudentsIndexRoute: typeof AuthStudentsIndexRoute
  AuthAdminServicesServiceIdRoute: typeof AuthAdminServicesServiceIdRoute
  AuthStudentsCourseCourseIdRoute: typeof AuthStudentsCourseCourseIdRoute
  AuthAdminCoursesIndexRoute: typeof AuthAdminCoursesIndexRoute
  AuthAdminServicesIndexRoute: typeof AuthAdminServicesIndexRoute
  AuthAdminCoursesManageCourseIdRoute: typeof AuthAdminCoursesManageCourseIdRouteWithChildren
  AuthStudentsCourseLessonLessonIdRoute: typeof AuthStudentsCourseLessonLessonIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminAllCoursesRoute: AuthAdminAllCoursesRoute,
  AuthAdminStudentsRoute: AuthAdminStudentsRoute,
  AuthStudentsAllCoursesRoute: AuthStudentsAllCoursesRoute,
  AuthStudentsMyCoursesRoute: AuthStudentsMyCoursesRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthStudentsIndexRoute: AuthStudentsIndexRoute,
  AuthAdminServicesServiceIdRoute: AuthAdminServicesServiceIdRoute,
  AuthStudentsCourseCourseIdRoute: AuthStudentsCourseCourseIdRoute,
  AuthAdminCoursesIndexRoute: AuthAdminCoursesIndexRoute,
  AuthAdminServicesIndexRoute: AuthAdminServicesIndexRoute,
  AuthAdminCoursesManageCourseIdRoute:
    AuthAdminCoursesManageCourseIdRouteWithChildren,
  AuthStudentsCourseLessonLessonIdRoute: AuthStudentsCourseLessonLessonIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
