/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as TrainingCourseIdRouteImport } from './routes/training/$courseId'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as AuthStudentsIndexRouteImport } from './routes/_auth/students/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthStudentsMyTrainingRouteImport } from './routes/_auth/students/my-training'
import { Route as AuthStudentsAllTrainingRouteImport } from './routes/_auth/students/all-training'
import { Route as AuthAdminStudentsRouteImport } from './routes/_auth/admin/students'
import { Route as AuthAdminAllTrainingRouteImport } from './routes/_auth/admin/all-training'
import { Route as AuthAdminTrainingIndexRouteImport } from './routes/_auth/admin/training/index'
import { Route as AuthAdminServicesIndexRouteImport } from './routes/_auth/admin/services/index'
import { Route as AuthAdminMembersIndexRouteImport } from './routes/_auth/admin/members/index'
import { Route as AuthStudentsTrainingCourseIdRouteImport } from './routes/_auth/students/training/$courseId'
import { Route as AuthAdminServicesServiceIdRouteImport } from './routes/_auth/admin/services/$serviceId'
import { Route as AuthStudentsTrainingLessonLessonIdRouteImport } from './routes/_auth/students/training/lesson/$lessonId'
import { Route as AuthAdminTrainingManageCourseIdRouteImport } from './routes/_auth/admin/training/manage/$courseId'
import { Route as AuthAdminTrainingManageCourseIdLessonsLessonIdRouteImport } from './routes/_auth/admin/training/manage/$courseId/lessons/$lessonId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const TrainingCourseIdRoute = TrainingCourseIdRouteImport.update({
  id: '/training/$courseId',
  path: '/training/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthStudentsIndexRoute = AuthStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsMyTrainingRoute = AuthStudentsMyTrainingRouteImport.update({
  id: '/students/my-training',
  path: '/students/my-training',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsAllTrainingRoute = AuthStudentsAllTrainingRouteImport.update({
  id: '/students/all-training',
  path: '/students/all-training',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminStudentsRoute = AuthAdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminAllTrainingRoute = AuthAdminAllTrainingRouteImport.update({
  id: '/admin/all-training',
  path: '/admin/all-training',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminTrainingIndexRoute = AuthAdminTrainingIndexRouteImport.update({
  id: '/admin/training/',
  path: '/admin/training/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminServicesIndexRoute = AuthAdminServicesIndexRouteImport.update({
  id: '/admin/services/',
  path: '/admin/services/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminMembersIndexRoute = AuthAdminMembersIndexRouteImport.update({
  id: '/admin/members/',
  path: '/admin/members/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsTrainingCourseIdRoute =
  AuthStudentsTrainingCourseIdRouteImport.update({
    id: '/students/training/$courseId',
    path: '/students/training/$courseId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminServicesServiceIdRoute =
  AuthAdminServicesServiceIdRouteImport.update({
    id: '/admin/services/$serviceId',
    path: '/admin/services/$serviceId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthStudentsTrainingLessonLessonIdRoute =
  AuthStudentsTrainingLessonLessonIdRouteImport.update({
    id: '/students/training/lesson/$lessonId',
    path: '/students/training/lesson/$lessonId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminTrainingManageCourseIdRoute =
  AuthAdminTrainingManageCourseIdRouteImport.update({
    id: '/admin/training/manage/$courseId',
    path: '/admin/training/manage/$courseId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminTrainingManageCourseIdLessonsLessonIdRoute =
  AuthAdminTrainingManageCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthAdminTrainingManageCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/training/$courseId': typeof TrainingCourseIdRoute
  '/services/': typeof ServicesIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/admin/all-training': typeof AuthAdminAllTrainingRoute
  '/admin/students': typeof AuthAdminStudentsRoute
  '/students/all-training': typeof AuthStudentsAllTrainingRoute
  '/students/my-training': typeof AuthStudentsMyTrainingRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/students/': typeof AuthStudentsIndexRoute
  '/admin/services/$serviceId': typeof AuthAdminServicesServiceIdRoute
  '/students/training/$courseId': typeof AuthStudentsTrainingCourseIdRoute
  '/admin/members/': typeof AuthAdminMembersIndexRoute
  '/admin/services/': typeof AuthAdminServicesIndexRoute
  '/admin/training/': typeof AuthAdminTrainingIndexRoute
  '/admin/training/manage/$courseId': typeof AuthAdminTrainingManageCourseIdRouteWithChildren
  '/students/training/lesson/$lessonId': typeof AuthStudentsTrainingLessonLessonIdRoute
  '/admin/training/manage/$courseId/lessons/$lessonId': typeof AuthAdminTrainingManageCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/training/$courseId': typeof TrainingCourseIdRoute
  '/services': typeof ServicesIndexRoute
  '/training': typeof TrainingIndexRoute
  '/admin/all-training': typeof AuthAdminAllTrainingRoute
  '/admin/students': typeof AuthAdminStudentsRoute
  '/students/all-training': typeof AuthStudentsAllTrainingRoute
  '/students/my-training': typeof AuthStudentsMyTrainingRoute
  '/admin': typeof AuthAdminIndexRoute
  '/students': typeof AuthStudentsIndexRoute
  '/admin/services/$serviceId': typeof AuthAdminServicesServiceIdRoute
  '/students/training/$courseId': typeof AuthStudentsTrainingCourseIdRoute
  '/admin/members': typeof AuthAdminMembersIndexRoute
  '/admin/services': typeof AuthAdminServicesIndexRoute
  '/admin/training': typeof AuthAdminTrainingIndexRoute
  '/admin/training/manage/$courseId': typeof AuthAdminTrainingManageCourseIdRouteWithChildren
  '/students/training/lesson/$lessonId': typeof AuthStudentsTrainingLessonLessonIdRoute
  '/admin/training/manage/$courseId/lessons/$lessonId': typeof AuthAdminTrainingManageCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/training/$courseId': typeof TrainingCourseIdRoute
  '/_public/': typeof PublicIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/_auth/admin/all-training': typeof AuthAdminAllTrainingRoute
  '/_auth/admin/students': typeof AuthAdminStudentsRoute
  '/_auth/students/all-training': typeof AuthStudentsAllTrainingRoute
  '/_auth/students/my-training': typeof AuthStudentsMyTrainingRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/students/': typeof AuthStudentsIndexRoute
  '/_auth/admin/services/$serviceId': typeof AuthAdminServicesServiceIdRoute
  '/_auth/students/training/$courseId': typeof AuthStudentsTrainingCourseIdRoute
  '/_auth/admin/members/': typeof AuthAdminMembersIndexRoute
  '/_auth/admin/services/': typeof AuthAdminServicesIndexRoute
  '/_auth/admin/training/': typeof AuthAdminTrainingIndexRoute
  '/_auth/admin/training/manage/$courseId': typeof AuthAdminTrainingManageCourseIdRouteWithChildren
  '/_auth/students/training/lesson/$lessonId': typeof AuthStudentsTrainingLessonLessonIdRoute
  '/_auth/admin/training/manage/$courseId/lessons/$lessonId': typeof AuthAdminTrainingManageCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/contact'
    | '/services/$serviceId'
    | '/training/$courseId'
    | '/services/'
    | '/training/'
    | '/admin/all-training'
    | '/admin/students'
    | '/students/all-training'
    | '/students/my-training'
    | '/admin/'
    | '/students/'
    | '/admin/services/$serviceId'
    | '/students/training/$courseId'
    | '/admin/members/'
    | '/admin/services/'
    | '/admin/training/'
    | '/admin/training/manage/$courseId'
    | '/students/training/lesson/$lessonId'
    | '/admin/training/manage/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/contact'
    | '/services/$serviceId'
    | '/training/$courseId'
    | '/services'
    | '/training'
    | '/admin/all-training'
    | '/admin/students'
    | '/students/all-training'
    | '/students/my-training'
    | '/admin'
    | '/students'
    | '/admin/services/$serviceId'
    | '/students/training/$courseId'
    | '/admin/members'
    | '/admin/services'
    | '/admin/training'
    | '/admin/training/manage/$courseId'
    | '/students/training/lesson/$lessonId'
    | '/admin/training/manage/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/login'
    | '/register'
    | '/_public/about'
    | '/_public/contact'
    | '/services/$serviceId'
    | '/training/$courseId'
    | '/_public/'
    | '/services/'
    | '/training/'
    | '/_auth/admin/all-training'
    | '/_auth/admin/students'
    | '/_auth/students/all-training'
    | '/_auth/students/my-training'
    | '/_auth/admin/'
    | '/_auth/students/'
    | '/_auth/admin/services/$serviceId'
    | '/_auth/students/training/$courseId'
    | '/_auth/admin/members/'
    | '/_auth/admin/services/'
    | '/_auth/admin/training/'
    | '/_auth/admin/training/manage/$courseId'
    | '/_auth/students/training/lesson/$lessonId'
    | '/_auth/admin/training/manage/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  TrainingCourseIdRoute: typeof TrainingCourseIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/training/$courseId': {
      id: '/training/$courseId'
      path: '/training/$courseId'
      fullPath: '/training/$courseId'
      preLoaderRoute: typeof TrainingCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/students/': {
      id: '/_auth/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthStudentsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/my-training': {
      id: '/_auth/students/my-training'
      path: '/students/my-training'
      fullPath: '/students/my-training'
      preLoaderRoute: typeof AuthStudentsMyTrainingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/all-training': {
      id: '/_auth/students/all-training'
      path: '/students/all-training'
      fullPath: '/students/all-training'
      preLoaderRoute: typeof AuthStudentsAllTrainingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/students': {
      id: '/_auth/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthAdminStudentsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/all-training': {
      id: '/_auth/admin/all-training'
      path: '/admin/all-training'
      fullPath: '/admin/all-training'
      preLoaderRoute: typeof AuthAdminAllTrainingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/training/': {
      id: '/_auth/admin/training/'
      path: '/admin/training'
      fullPath: '/admin/training/'
      preLoaderRoute: typeof AuthAdminTrainingIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/services/': {
      id: '/_auth/admin/services/'
      path: '/admin/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AuthAdminServicesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/members/': {
      id: '/_auth/admin/members/'
      path: '/admin/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AuthAdminMembersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/training/$courseId': {
      id: '/_auth/students/training/$courseId'
      path: '/students/training/$courseId'
      fullPath: '/students/training/$courseId'
      preLoaderRoute: typeof AuthStudentsTrainingCourseIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/services/$serviceId': {
      id: '/_auth/admin/services/$serviceId'
      path: '/admin/services/$serviceId'
      fullPath: '/admin/services/$serviceId'
      preLoaderRoute: typeof AuthAdminServicesServiceIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students/training/lesson/$lessonId': {
      id: '/_auth/students/training/lesson/$lessonId'
      path: '/students/training/lesson/$lessonId'
      fullPath: '/students/training/lesson/$lessonId'
      preLoaderRoute: typeof AuthStudentsTrainingLessonLessonIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/training/manage/$courseId': {
      id: '/_auth/admin/training/manage/$courseId'
      path: '/admin/training/manage/$courseId'
      fullPath: '/admin/training/manage/$courseId'
      preLoaderRoute: typeof AuthAdminTrainingManageCourseIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/training/manage/$courseId/lessons/$lessonId': {
      id: '/_auth/admin/training/manage/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/training/manage/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AuthAdminTrainingManageCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AuthAdminTrainingManageCourseIdRoute
    }
  }
}

interface AuthAdminTrainingManageCourseIdRouteChildren {
  AuthAdminTrainingManageCourseIdLessonsLessonIdRoute: typeof AuthAdminTrainingManageCourseIdLessonsLessonIdRoute
}

const AuthAdminTrainingManageCourseIdRouteChildren: AuthAdminTrainingManageCourseIdRouteChildren =
  {
    AuthAdminTrainingManageCourseIdLessonsLessonIdRoute:
      AuthAdminTrainingManageCourseIdLessonsLessonIdRoute,
  }

const AuthAdminTrainingManageCourseIdRouteWithChildren =
  AuthAdminTrainingManageCourseIdRoute._addFileChildren(
    AuthAdminTrainingManageCourseIdRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAdminAllTrainingRoute: typeof AuthAdminAllTrainingRoute
  AuthAdminStudentsRoute: typeof AuthAdminStudentsRoute
  AuthStudentsAllTrainingRoute: typeof AuthStudentsAllTrainingRoute
  AuthStudentsMyTrainingRoute: typeof AuthStudentsMyTrainingRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthStudentsIndexRoute: typeof AuthStudentsIndexRoute
  AuthAdminServicesServiceIdRoute: typeof AuthAdminServicesServiceIdRoute
  AuthStudentsTrainingCourseIdRoute: typeof AuthStudentsTrainingCourseIdRoute
  AuthAdminMembersIndexRoute: typeof AuthAdminMembersIndexRoute
  AuthAdminServicesIndexRoute: typeof AuthAdminServicesIndexRoute
  AuthAdminTrainingIndexRoute: typeof AuthAdminTrainingIndexRoute
  AuthAdminTrainingManageCourseIdRoute: typeof AuthAdminTrainingManageCourseIdRouteWithChildren
  AuthStudentsTrainingLessonLessonIdRoute: typeof AuthStudentsTrainingLessonLessonIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminAllTrainingRoute: AuthAdminAllTrainingRoute,
  AuthAdminStudentsRoute: AuthAdminStudentsRoute,
  AuthStudentsAllTrainingRoute: AuthStudentsAllTrainingRoute,
  AuthStudentsMyTrainingRoute: AuthStudentsMyTrainingRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthStudentsIndexRoute: AuthStudentsIndexRoute,
  AuthAdminServicesServiceIdRoute: AuthAdminServicesServiceIdRoute,
  AuthStudentsTrainingCourseIdRoute: AuthStudentsTrainingCourseIdRoute,
  AuthAdminMembersIndexRoute: AuthAdminMembersIndexRoute,
  AuthAdminServicesIndexRoute: AuthAdminServicesIndexRoute,
  AuthAdminTrainingIndexRoute: AuthAdminTrainingIndexRoute,
  AuthAdminTrainingManageCourseIdRoute:
    AuthAdminTrainingManageCourseIdRouteWithChildren,
  AuthStudentsTrainingLessonLessonIdRoute:
    AuthStudentsTrainingLessonLessonIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  TrainingCourseIdRoute: TrainingCourseIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
